# Generated by Django 4.2 on 2024-01-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
