# Generated by Django 4.2 on 2024-01-01 12:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_blogpost_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
